SPRINT 2 DE DEV VERS MAIN
WildCodeSchool/2023-09-JS-Lyon-P2-GROUP-Mechka pull request #18
Opened 2023-11-09 15:33 UTC by axelarese

SPRINT 2 - Terminé avec correction des bugs.

Les US réalisées : 
- US 2 : Affichage des show et du caroussel.
- US 4 et 5 : Possibilité de cliquer sur les albums pour accéder aux différentes musiques.
- US 10, 11 et 12 : Création de la searchbar et possibilité de rechercher des albums.

2023-11-09 22:43 UTC, HazeFury commented on frontend/src/components/carrouselDesktop/CarrouselDesktop.jsx
Aucun code dans ce fichier. Si le fichier est inutile => go le supprimer

2023-11-09 22:44 UTC, HazeFury commented on frontend/src/components/carrouselDesktop/CarrouselDesktop.module.css
Idem que pour .jsx

2023-11-09 23:00 UTC, HazeFury commented on frontend/src/components/list/ArtistsList.jsx
> +      .then((data) => setartists(data.artists));
Que se passe-t-il en cas d'erreur (si le fetch ne marche pas) ?? Il faut gérer les erreurs ^^

2023-11-09 23:03 UTC, HazeFury commented on frontend/src/components/list/List.jsx
> +        setAlbums(data.items);
Idem pour la gestion des erreurs

2023-11-09 23:07 UTC, HazeFury commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +  }, [token]);
Idem pour la gestion des erreurs

2023-11-09 23:13 UTC, HazeFury commented on frontend/src/components/navBar/NavBar.jsx
Petite astuce : vous pouvez créer des petits composants JSX contenant votre code SVG. Cela évite trop charger le fichier navbar =)

Là c'est ok car vous avez uniquement vos SVG mais si il y avait plus de code, il faudrait les ranger dans des sous-composants ^^

2023-11-09 23:17 UTC, HazeFury commented on frontend/src/pages/home/HomeCss.css
Le fichier homeCss est vide donc à supprimer si inutilisé + le nom homeCss.css est pas top ^^ home.css ferait l'affaire =D

2023-11-09 23:20 UTC, HazeFury requested changes
C'est du très bon travail, BRAVO à tous !!! 

Il y a quelques petits trucs à corriger mais rien de bien grave ^^

Hâte de voir la suite =)

2023-11-10 00:15 UTC, wildmatthieu commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +    if (!token) return;
#meilleure-lecture-du-code
Explicitez votre condition 

`token !== null` ? 
`token !== ""` ? 
...

2023-11-10 00:15 UTC, wildmatthieu commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +          {newShows &&
Explicitez votre condition : 
`newShows !== null` ? 
`newShows !== ""` ? 
...

2023-11-10 00:15 UTC, wildmatthieu commented on frontend/src/pages/home/Home.jsx
> +      <NavBar />
quel lien y a t-il entre le déplacement du composant NavBar et le but de l'US ?

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.jsx
> +    if (!token) {
explicitez la condition : 
`token === null` ? 
`token === undefined` ? 
...

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.jsx
> +      {!album && <p className={style.paraphLoading}>Loading...</p>}
explicitez la condition : 
`album === null && ...` ? 
`album === undefined && ...` ? 
...

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.jsx
> +        {album && (
explicitez la condition : 
`album !== null && ...` ? 
`album !== undefined && ...` ? 
...

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.module.css
> +  /* margin: 5rem; */
commentaire à retirer

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.module.css
> +  /* margin-left: 5rem; */
commentaire à retirer

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/Album.module.css
> +  /* justify-content: center; */
commentaire à retirer

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/AlbumMain.module.css
> +.artistName {
blocs de commentaires à retirer ici et en dessous

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/album/AlbumTrack.jsx
> +          <p>{replaceString((duration / 60000).toFixed(2))}</p>
60000 est un chifre magique
=> ajouter un commentaire pour préciser à quoi il corresponds, et pouquoi l'avoir choisi

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/carrouselMain/CarrouselContainer.jsx
>          {newReleases &&
condition à expliciter : 
`newReleases !== null && ...`
`newReleases !== "" && ...`

2023-11-10 00:23 UTC, wildmatthieu commented on frontend/src/components/navBar/NavBar.jsx
Éventuellement à ajouter dans une US "improve" pour le prochain sprint

2023-11-10 00:31 UTC, wildmatthieu commented on frontend/src/pages/list/ArtistsList.jsx
> +    if (!token) return;
Explicitez la condition : 
`token === false` ?
`token === null` ?
...

2023-11-10 00:31 UTC, wildmatthieu commented on frontend/src/pages/list/ArtistsList.jsx
> +      {artists &&
Explicitez la condition : 
`artists !== [] && ...`
`artists !== undefined && ...` 
...

2023-11-10 00:31 UTC, wildmatthieu commented on frontend/src/pages/list/List.jsx
> +        {searchInput || <ArtistsList />}
Explicitez la condition : 
`searchInput !== null || ...` ?
`searchInput !== undefined || ...` ?
...

2023-11-10 00:34 UTC, wildmatthieu commented on frontend/src/pages/home/HomeCss.css
Le fichier ne semble pas vide non ? 
Je vois le code 
```
.Homepage {
  height: 100%;
}
```

dedans

2023-11-10 00:36 UTC, wildmatthieu commented on frontend/src/pages/home/HomeCss.css
> +.Homepage {
N'utilisez les majuscules que si cela apporte une information précise 
Si il n'y a pas de raison particulière d'utiliser un H majuscule dans `Homepage`
Remplacer `Homepage` par `homepage`

2023-11-10 00:39 UTC, wildmatthieu commented on frontend/src/components/album/AlbumTrack.jsx
> +            {replaceString((duration / 60000).toFixed(2))}
chiffre 60000 'magique'
Ajoutez en commentaire la signifiaction et le choix de ce chiffre

2023-11-10 00:43 UTC, wildmatthieu commented on frontend/package.json
> +    "react-responsive-3d-carousel": "^1.3.0",
(juste à titre informatif) 
Point de vigilance à avoir lorsqu'on prend un package extérieur 

![image](https://github.com/WildCodeSchool/2023-09-JS-Lyon-P2-GROUP-Mechka/assets/144900231/158428af-7f9a-4e3f-a192-118848617f7d)

Inactively Maintained : 

![image](https://github.com/WildCodeSchool/2023-09-JS-Lyon-P2-GROUP-Mechka/assets/144900231/cf779829-6114-4bc1-8801-252604c87a85)

2023-11-10 00:46 UTC, wildmatthieu commented on frontend/src/components/mainShows/MainShowsContainer.jsx
>            {!newShows && <p>Loading...</p>}
Condition à expliciter : 

`newShows === null && ...` ?
`newShows === [] && ...` ?
...

2023-11-10 00:46 UTC, wildmatthieu commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +            {newShows &&
Condition à expliciter : 

`newShows !== null && ...` ?
`newShows !== [] && ...` ?
`newShows !== undefined && ...` ?
...

2023-11-10 08:21 UTC, Bak-Faek commented on frontend/src/components/album/Album.jsx
> +    if (!token) {
ok

2023-11-10 08:22 UTC, Bak-Faek commented on frontend/src/components/album/Album.jsx
> +      {!album && <p className={style.paraphLoading}>Loading...</p>}
ok

2023-11-10 08:22 UTC, Bak-Faek commented on frontend/src/components/album/Album.jsx
> +        {album && (
ok

2023-11-10 08:23 UTC, axelarese commented on frontend/src/components/album/Album.module.css
> +  /* margin: 5rem; */
OK

2023-11-10 08:23 UTC, axelarese commented on frontend/src/components/album/Album.module.css
> +  /* margin-left: 5rem; */
OK

2023-11-10 08:23 UTC, axelarese commented on frontend/src/components/album/Album.module.css
> +  /* justify-content: center; */
OK

2023-11-10 08:23 UTC, axelarese commented on frontend/src/components/album/AlbumMain.module.css
> +.artistName {
OK

2023-11-10 08:25 UTC, axelarese commented on frontend/src/components/album/AlbumTrack.jsx
> +          <p>{replaceString((duration / 60000).toFixed(2))}</p>
OK

2023-11-10 08:27 UTC, axelarese commented on frontend/src/pages/list/ArtistsList.jsx
> +    if (!token) return;
OK

2023-11-10 08:27 UTC, axelarese commented on frontend/src/pages/list/ArtistsList.jsx
> +      {artists &&
OK

2023-11-10 08:30 UTC, axelarese commented on frontend/src/pages/list/List.jsx
> +        {searchInput || <ArtistsList />}
OK

2023-11-10 08:31 UTC, axelarese commented on frontend/src/pages/home/HomeCss.css
> +.Homepage {
OK

2023-11-10 08:31 UTC, axelarese commented on frontend/src/components/album/AlbumTrack.jsx
> +            {replaceString((duration / 60000).toFixed(2))}
OK

2023-11-10 08:31 UTC, axelarese commented on frontend/package.json
> +    "react-responsive-3d-carousel": "^1.3.0",
OK

2023-11-10 08:32 UTC, Bak-Faek commented on frontend/src/components/carrouselDesktop/CarrouselDesktop.jsx
ok

2023-11-10 08:32 UTC, Bak-Faek commented on frontend/src/components/carrouselDesktop/CarrouselDesktop.module.css
ok

2023-11-10 08:32 UTC, Bak-Faek commented on frontend/src/pages/home/HomeCss.css
ok

2023-11-10 08:33 UTC, Bak-Faek commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +    if (!token) return;
ok

2023-11-10 08:33 UTC, Bak-Faek commented on frontend/src/components/mainShows/MainShowsContainer.jsx
>            {!newShows && <p>Loading...</p>}
ok

2023-11-10 08:34 UTC, Bak-Faek commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +            {newShows &&
ok

2023-11-10 08:43 UTC, Bak-Faek commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +          {newShows &&
ok

2023-11-10 09:05 UTC, Bak-Faek commented on frontend/src/components/mainShows/MainShowsContainer.jsx
> +  }, [token]);
ok

2023-11-10 09:07 UTC, Bak-Faek commented on frontend/src/components/list/ArtistsList.jsx
> +      .then((data) => setartists(data.artists));
ok

2023-11-10 10:44 UTC, merged